// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetIndexHandlerFunc turns a function with the right signature into a get index handler
type GetIndexHandlerFunc func(GetIndexParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIndexHandlerFunc) Handle(params GetIndexParams) middleware.Responder {
	return fn(params)
}

// GetIndexHandler interface for that can handle valid get index params
type GetIndexHandler interface {
	Handle(GetIndexParams) middleware.Responder
}

// NewGetIndex creates a new http.Handler for the get index operation
func NewGetIndex(ctx *middleware.Context, handler GetIndexHandler) *GetIndex {
	return &GetIndex{Context: ctx, Handler: handler}
}

/*GetIndex swagger:route GET / getIndex

GetIndex get index API

*/
type GetIndex struct {
	Context *middleware.Context
	Handler GetIndexHandler
}

func (o *GetIndex) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetIndexParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
