// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetIndexOKCode is the HTTP code returned for type GetIndexOK
const GetIndexOKCode int = 200

/*GetIndexOK Returns the Dashboard homepage.

swagger:response getIndexOK
*/
type GetIndexOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetIndexOK creates GetIndexOK with default headers values
func NewGetIndexOK() *GetIndexOK {

	return &GetIndexOK{}
}

// WithPayload adds the payload to the get index o k response
func (o *GetIndexOK) WithPayload(payload string) *GetIndexOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get index o k response
func (o *GetIndexOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndexOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
