// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetModelOKCode is the HTTP code returned for type GetModelOK
const GetModelOKCode int = 200

/*GetModelOK Returns a description of the currently running model.

swagger:response getModelOK
*/
type GetModelOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetModelOK creates GetModelOK with default headers values
func NewGetModelOK() *GetModelOK {

	return &GetModelOK{}
}

// WithPayload adds the payload to the get model o k response
func (o *GetModelOK) WithPayload(payload interface{}) *GetModelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get model o k response
func (o *GetModelOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetModelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
