// Code generated by go-swagger; DO NOT EDIT.

// Package restapi My FastScore Microservice
//
//  An example FastScore microservice.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - text/html
//    - application/json
//
// swagger:meta
package restapi
