// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "An example FastScore microservice.",
    "title": "My FastScore Microservice",
    "version": "0.1"
  },
  "paths": {
    "/": {
      "get": {
        "produces": [
          "text/html"
        ],
        "operationId": "get_index",
        "responses": {
          "200": {
            "description": "Returns the Dashboard homepage.",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/{engine}/model": {
      "get": {
        "produces": [
          "application/json"
        ],
        "operationId": "get_model",
        "parameters": [
          {
            "type": "string",
            "description": "The name of the engine instance",
            "name": "engine",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a description of the currently running model.",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "An example FastScore microservice.",
    "title": "My FastScore Microservice",
    "version": "0.1"
  },
  "paths": {
    "/": {
      "get": {
        "produces": [
          "text/html"
        ],
        "operationId": "get_index",
        "responses": {
          "200": {
            "description": "Returns the Dashboard homepage.",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/{engine}/model": {
      "get": {
        "produces": [
          "application/json"
        ],
        "operationId": "get_model",
        "parameters": [
          {
            "type": "string",
            "description": "The name of the engine instance",
            "name": "engine",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns a description of the currently running model.",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    }
  }
}`))
}
